/**
 * 애플리케이션 전역 에러 코드
 * 모든 서비스에서 일관된 에러 코드를 사용하기 위해 중앙 관리
 */
export const ErrorCodes = {
  // User 관련
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_CREATE_FAILED: 'USER_CREATE_FAILED',
  USER_QUERY_ERROR: 'USER_QUERY_ERROR',

  // Subscription 관련
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_CREATE_FAILED: 'SUBSCRIPTION_CREATE_FAILED',
  SUBSCRIPTION_QUERY_ERROR: 'SUBSCRIPTION_QUERY_ERROR',
  ALREADY_SUBSCRIBED: 'ALREADY_SUBSCRIBED',
  INVALID_BILLING_KEY: 'INVALID_BILLING_KEY',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',

  // External Service 관련
  GEMINI_TIMEOUT: 'GEMINI_TIMEOUT',
  GEMINI_AUTH_ERROR: 'GEMINI_AUTH_ERROR',
  GEMINI_RATE_LIMIT: 'GEMINI_RATE_LIMIT',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  CLERK_API_ERROR: 'CLERK_API_ERROR',

  // Database 관련
  DATABASE_ERROR: 'DATABASE_ERROR',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_QUERY_PARAMS: 'INVALID_QUERY_PARAMS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
